apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "watchmarket.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      protocol: TCP
      name: http
    - port: 8081
      protocol: TCP
      name: swagger
  selector:
      name: nginx-proxy